### ISSUE TITLE
Building justbuild fails with GCC 13.2 due to  `partial specialization of ‘struct fmt::v10::formatter<std::__cxx11::basic_string<...>>`

### ISSUE THREAD

**Issue by mhthies** [just-buildsystem/justbuild#43]
I tried to change my Arch Linux package recipe to use GCC instead of Clang and ran into another {fmt}-related issue:

```txt
In file included from /usr/include/fmt/ostream.h:20,
                 from /home/michael/Documents/Freizeit/Programme/pkgbuild/justbuild/src/build/src/src/utils/cpp/json.hpp:25,
                 from /home/michael/Documents/Freizeit/Programme/pkgbuild/justbuild/src/build/src/src/buildtool/common/artifact_description.hpp:27,
                 from /home/michael/Documents/Freizeit/Programme/pkgbuild/justbuild/src/build/src/src/buildtool/build_engine/expression/target_result.hpp:23,
                 from /home/michael/Documents/Freizeit/Programme/pkgbuild/justbuild/src/build/src/src/buildtool/build_engine/expression/target_result.cpp:15:
/usr/include/fmt/format.h:4076:1: error: partial specialization of ‘struct fmt::v10::formatter<std::__cxx11::basic_string<_CharT>, Char>’ after instantiation of ‘struct fmt::v10::formatter<std::__cxx11::basic_string<char>, char, void>’ [-fpermissive]
 4076 | FMT_FORMAT_AS(std::basic_string<Char>, basic_string_view<Char>);
      | ^~~~~~~~~~~~~
```

(and many similar occurances; all of them caused by `artifact_description.hpp` being included somehow.)

This might be introduced by my patch (#42) and sounds similar to this issue: https://github.com/fmtlib/fmt/issues/2769

I was able to fully fix the problem by replacing the `#include "fmt/core.h"` with `#include "fmt/format.h"` in logger.hpp.

Tested with fmt 10.1.0.

**Comment by spc90** [comment]
Hi @mhthies ! Thank you for your report.

We are currently having trouble reproducing this in our pipelines. The issue seems to be more related to [fmtlib/fmt#3584](https://github.com/fmtlib/fmt/issues/3584), which would explain also the temporary fix of reordering/replacing the include. We have bumped up our fmt version to 10.1.1 (commit [f969ab6](https://github.com/just-buildsystem/justbuild/commit/f969ab6c3d1c4e38f0c73ccfb4f6ebbe3ed9286a)) which contains an upstream fix for this issue.

Could you please check if this solves it on your side?

**Comment by mhthies** [comment]
Thanks for investigating this issue! :)

You are right: Updating to fmt 10.1.1 fixes the issue. Now, I'll only have to wait for the Arch Linux package maintainer to package this fmt version.
